### ISSUE TITLE
Operational Readiness

### ISSUE THREAD

**Issue by arein** [WalletConnect/cast-server#12]
O11Y:
- [x] #13
- [x] Setup dashboard start with https://g-49ef0030d2.grafana-workspace.eu-central-1.amazonaws.com/d/prod-push/prod-push?orgId=1
- [x] Add databases / downstream dependencies to dashboard
- [x] Add to `status.walletconnect.com`
- [x] Install alarms

Pipeline/Testing:
- [x] Functional tests
- [x] Integration tests
- [ ] Integrate with `push-test.walletconnect.com`
- [x] #36 
- [x] #37 
- [x] #35 

Logging
- [x] Sort out what we should log and log it

Ops:
- [x] Write Runbook entry for each monitor/alarm

Analytics:
- [x] Data Lake integration

**Comment by chris13524** [comment]
> Write runbook entry for each monitor/alarm

I will write this as I encounter alarms going forward. I checked the box.

> Data Lake integration

Complete. I checked the box. https://github.com/WalletConnect/notify-server/blob/7d713b6349f8e3595cec83b7f3dd2bdc91de9b51/src/handlers/notify.rs#L172

**Comment by chris13524** [comment]
Closing as these issues have all been addressed or moved to Notify Server repo
