### ISSUE TITLE
Cast server needs to monitor CPU/disk/FreeableMemory for DocumentDB

### ISSUE THREAD

**Issue by arein** [WalletConnect/cast-server#23]
COE follow up

**Comment by chris13524** [comment]
Is this implemented in the latest dashboard? https://g-e66b9a1a24.grafana-workspace.eu-central-1.amazonaws.com/d/prod-cast/prod-cast-server?orgId=1

**Comment by chris13524** [comment]
Implemented for RDS in Notify Server: https://github.com/WalletConnect/notify-server/pull/141
