### ISSUE TITLE
Relay websocket not meeting the user_agent spec

### ISSUE THREAD

**Issue by arein** [WalletConnect/cast-server#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![screenshot_2023-05-31_at_11 11 30_am_720](https://github.com/WalletConnect/cast-server/assets/966091/0dc446b4-c12d-43ae-9c26-dbfec0b86e6f)

### Expected Behavior

User agent meets the spec of the other SDKs

### Steps To Reproduce

See https://deepnote.com/workspace/walletconnect-89824fe5-4737-41db-9481-c2734cb6a57f/project/Weird-RPC-IDs-97aa51d5-c9b4-4979-adda-d9831fc04391/notebook/Notebook%201-7cb153ecd7354ad9a97a6704237100db

### Environment

```markdown
- OS:
- rustc:
- cargo:
```

**Comment by Rakowskiii** [comment]
Done w
