### ISSUE TITLE
E2E: Cover Relay notification sending

### ISSUE THREAD

**Issue by arein** [WalletConnect/cast-server#39]
Currently Cast tests cover that it hands a message to the Relay. We do not cover that the Relay hands that message further along. That should be covered.

**Comment by chris13524** [comment]
Closing as this has been implemented in notify server: https://github.com/WalletConnect/notify-server/blob/cfcf3e003d42ea397230dab450f53a019ca495ae/tests/integration.rs#L297C29-L297C43
