### ISSUE TITLE
Refactor from Cast to Notify Server

### ISSUE THREAD

**Issue by Rakowskiii** [WalletConnect/cast-server#49]
Refactor the code getting rid of old "Cast" functionalities (http) moving to new, `push_subscribe` flow.

The refactor should be modular allowing for simple change from websockets to webhooks once it's ready.

- [ ] Remove register HTTP endpoint
- [ ] Rename Cast to Notify in separate repo
- [ ] Deploy under `https://notify.walletconnect.com` (To be confirmed)

**Comment by chris13524** [comment]
Closing as changes have been implemented in https://github.com/walletconnect/notify-server
