### ISSUE TITLE
Log message id's

### ISSUE THREAD

**Issue by Rakowskiii** [WalletConnect/cast-server#81]
https://walletconnect.slack.com/archives/C03RWGSBCUU/p1687525918928309?thread_ts=1687517439.299879&cid=C03RWGSBCUU

**Comment by chris13524** [comment]
Closing as this is already implemented in notify-server: https://github.com/WalletConnect/notify-server/blob/7d713b6349f8e3595cec83b7f3dd2bdc91de9b51/src/handlers/notify.rs#L172
